### ISSUE TITLE
scraping_servise

### ISSUE THREAD

**Issue by YauheniLiubich** [olegJF/scraping_service#2]
При запуске run_scraping.py вылазит ошибка django.db.utils.IntegrityError: NOT NULL constraint failed: scraping_vacancy.city_id
с чем это связано?  уже все перепроверил, согласно вашим урокам.... вроде все один в один с тем как у Вас, и все равно ошибка

**Comment by olegJF** [comment]
Здравствуйте!
Проблема в том, что Вы не передаете значения города при сохранении
вакансии. Сложно сказать с чем это связано.
Дайте ссылку на Ваш гитХаб, чтобы я мог посмотреть на код.
С уважением, Олег.

сб, 1 авг. 2020 г. в 19:30, Evgeniy <notifications@github.com>:

**Comment by YauheniLiubich** [comment]
https://github.com/EvgeniyLiubich/scraping_service.git
Если через админку очистить список вакансий, то программа запускается и список вакансий наполняется.... И если повторно запустить, предварительно не очистив список вакансий, то вылазит именно эта ошибка django.db.utils.IntegrityError: NOT NULL constraint failed: scraping_vacancy.city_id
т е оно работает, когда список вакансий пуст
не могу найти где я накосячил

**Comment by olegJF** [comment]
Евгений, здравствуйте!
К сожалению я не могу зайти в репозиторий - видимо он у Вас приватный.
Добавьте меня в список аккаунтов, у которых есть доступ.
С уважением, Олег

вс, 2 авг. 2020 г. в 16:31, Evgeniy <notifications@github.com>:

**Comment by YauheniLiubich** [comment]
Извините, как то не подумал, что репозиторий приватный =)
добавил Вас =)
Буду очень благодарен, если поможете =)

**Comment by olegJF** [comment]
Интересно. Внешне, вроде бы все правильно. 

Проверил, все работает. Я полностью использовал Ваш код, только лишь добавил свои парсеры - этой ошибки нет! 
Как вариант, попробуйте запустить скрипт в режиме дебага, чтобы проверить в какой момент вылетает ошибка, тогда будет проще найти причину.

пн, 3 авг. 2020 г. в 16:08, Evgeniy <notifications@github.com>:

**Comment by YauheniLiubich** [comment]
Я запускал в режиме дебага
ошибка вылазит именно в момент сохранения, при вызове v.save()
т.е 
v = Vacancy(**job)
это отрабатывает, инстанс создается, но при попытке сохранить выскакивает такая ошибка...

**Comment by YauheniLiubich** [comment]
и еще я столкнулся с такой ошибкой:
вот я создал через админку еще одного пользователя (ну, естественно суперпользователь тоже есть)
т е по факту есть два пользователя...
допустим города у них одинаковые, а вот языки программирования допустим один Python, другой  Java
у нас есть функция get_urls
в начале мы получаем кортежи с id города и ЯП 
 qs = Url.objects.all().values() 
получается создается 2 кортежа: (1, 11) и (1, 12)
цикл с кортежем (1, 11) успешно выполняется, как и у вас .... но вот когда цикл
начинает работать со вторым кортежем, то тут выскакивает ошибка 
KeyError: (1, 12)
![KeyError](https://user-images.githubusercontent.com/65807319/89206943-a19cc900-d5c2-11ea-865d-4b891de14abd.png)

Я просто еще не опытный , точнее очень зеленый =)) часа 3 убил, но так и не разобрался почему такая ошибка выскакивает
Извините за мою настойчивость и беспокойство, но кроме автора этого курса я и не знаю у кого спросить что да как =)

**Comment by YauheniLiubich** [comment]
И еще такой вопрос, по быстродействию 
вот я ищу всего на двух сайтах, а вы на пяти вроде бы
у меня время работы именно части кода, которая парсит без использования Asyncio  составляет 4,73 секунды, с использованием - 3,61 секунда
у вас выгрыш во времени был в 3 раза, а у меня не такой большой выигрыш ... тем более если учесть, что у меня идет сбор информации всего с двух сайтов....
а полный цикл выполнения программы длится аж целых 57,24 секунды!!! Это так и должно быть так долго?

**Comment by olegJF** [comment]
Здравствуйте!

> v = Vacancy(**job)

как раз нужно подебажить что приходит в записях jobs. Однозначно, в какой-то из записей отсутствует значение для city_id и нужно найти причину, почему это происходит.
Если не получиться найти причину, то сделайте дамп базы данных и разместите его у себя в репозитории, чтобы я мог используя Ваши настройки попытаться отловить ошибку. 
`python manage.py dumpdata accounts scraping > data.json`

> выскакивает ошибка KeyError: (1, 12)

Это происходит потому, что в наборе урлов для парсинга, отсутствует такой ключ. Другими словами - у Вас нет в модели Url записи, соответствующей набору, где город_айди = 1, а яп_айди = 12. 
Благодаря Вам, я вчера увидел это потенциально опасное место в коде и внес изменения https://github.com/olegJF/scraping_service/commit/3b6b65655dcc17f92d50456bf190e6aaeefbcdd3

> И еще такой вопрос, по быстродействию

Тут чем больше функций парсинга, тем больше выигрыш по времени. Поскольку в синхронном режиме они запускаются друг за другом, т.е. общее время суммируется, а в асинхронном, они запускаются параллельно и общее время равно максимальному времени обработки одного из парсеров для разового запуска для одной пары город, ЯП.

> а полный цикл выполнения программы длится аж целых 57,24 секунды!!! Это так и должно быть так долго?

По идее нет. Нужно смотреть, какая операция выполняется дольше всего - запуск проекта, парсинг или сохранение результатов. После этого разбираться в чем причина.
С уважением, Олег

**Comment by YauheniLiubich** [comment]
Добрый день
что то совсем никак не могу победить эту ошибку
Запускаю дебаг
![1](https://user-images.githubusercontent.com/65807319/89640209-bf667880-d8b7-11ea-9cab-2cd1bdb744f6.png)
![1 1](https://user-images.githubusercontent.com/65807319/89640216-c3929600-d8b7-11ea-83fc-b71e872a5b91.png)
Далее видно, что job это полноценный словарь для одной вакансии с соответствующими заголовками.... т е у нас есть все, чтобы создать инстас класса Vacancy
Но с другой то стороны, у нас уже такой инстатс в базе данных есть, один в один... Это же старое объявление....
Я только не пойму, почему **job не распаковывается полностью , а только ключ 'title'
![2](https://user-images.githubusercontent.com/65807319/89640447-41ef3800-d8b8-11ea-8134-33862ef97d16.png)
ну и далее процесс сохранения не происходит, выбрасывает исключение
![3 1](https://user-images.githubusercontent.com/65807319/89640555-7f53c580-d8b8-11ea-9154-c4d2df00daf9.png)
![3](https://user-images.githubusercontent.com/65807319/89640566-8084f280-d8b8-11ea-8a21-5dc42009e19d.png)

**Comment by YauheniLiubich** [comment]
Хотя, я обратил внимание, что в БД все таки новые объявления добавляются....
Может это и должно так работать?
Раньше этого я не замечал, т к все делал в один день и возможно новых объявлений попросту на сайтах не было...
А по поводу быстродействия: может у меня так долго выполняется, потому что оно за раз находит порядка 600 вакансий?
Потому что первый раз запускается?
Я сегодня запустил, вся программа выполнилась за 8 секунд и было добавлено порядка 100 вакансий новых

**Comment by olegJF** [comment]
Добрый день.

> Я только не пойму, почему **job не распаковывается полностью , а только ключ 'title'

Судя по скриншоту, распаковался полностью - есть все ключи и их значения.
![89640447-41ef3800-d8b8-11ea-8134-33862ef97d16](https://user-images.githubusercontent.com/15360182/89642682-e96e6980-d8bc-11ea-921e-925216d44eae.png)


> ну и далее процесс сохранения не происходит, выбрасывает исключение

Какое исключение срабатывает? Если оно связано с тем, что данная запись уже есть в БД, то так и должно быть! Тем самым мы не создаем дубликаты, а добавляем лишь новые записи. Можно перед сохранением проверять наличие записи с таким же урлом и если она есть, то не добавлять. А можно сохранение обвесить конструкцией try\except и не заморачиваться лишними проверками.
 

> А по поводу быстродействия: может у меня так долго выполняется, потому что оно за раз находит порядка 600 вакансий?

Однозначно, чем больший объем данных нужно обработать, тем дольше будет работать функция.
