### ISSUE TITLE
scraping_service проблема с добавлением нового ресурса

### ISSUE THREAD

**Issue by belo404ka** [olegJF/scraping_service#3]
Добрый день! Помогите, пожалуйста, советом. В папку parsers,py добавила еще один сайт, в папке work.txt видно, что все правильно обрабатывается. Добавила url этого сайта в models и run_scraping. В админке на сайте url тоже сохранился как и остальные, указала правильный путь, такой же как и при проверке в файле parsers. Создала новый url для другого городаБ запускаю файлы и иду смотреть на сайт вакансии-результата нет. Почему-то не сохраняется в бд. Не могу понять в чем ошибка. На гите есть директория-parkovka
вот ссылка https://github.com/belo404ka/parkovka

**Comment by olegJF** [comment]
Зддравствуйте!
Вариантов, почему это происходит, может быть масса. Попробуйте для начала, посмотреть на содержимое списка с урлами для парсинга https://github.com/belo404ka/parkovka/blob/master/run_scraping.py#L63
Если там нет урла для rabru, то нужно смотреть, почему он туда не добавляется (возможно нет нужного сочетания город\ЯП).
Если урл есть, тогда нужно смотреть результаты работы парсеров https://github.com/belo404ka/parkovka/blob/master/run_scraping.py#L82 (список со словарями jobs)
Если и там есть результаты работы парсера rabru (это видно по урлам), тогда нужно дебажить сам процесс записи данных в БД - https://github.com/belo404ka/parkovka/blob/master/run_scraping.py#L85
Дума, что эти шаги помогут Вам разобраться в причинах :)
С уважением, Олег.
